### ISSUE TITLE
This is not ”” but ""(bouble quote)

### ISSUE THREAD

**Issue by HikaruEgashira** [KanadeNishizawa/Portfolio#1]
https://github.com/KanadeNishizawa/Portfolio/blob/cf422a4eeacbea9ba7760c4d0e5b0b32d2b6b138/pf.works.html#L18

HtmlHint: The value of attribute [ class ] must be in double quotes.(attr-value-double-quotes)

**Comment by HikaruEgashira** [comment]
The value of attribute [ id ] must be in double quotes.(attr-value-double-quotes)

https://github.com/KanadeNishizawa/Portfolio/blob/cf422a4eeacbea9ba7760c4d0e5b0b32d2b6b138/pf.works.html#L66

https://github.com/KanadeNishizawa/Portfolio/blob/cf422a4eeacbea9ba7760c4d0e5b0b32d2b6b138/pf.works.html#L113

**Comment by HikaruEgashira** [comment]
Tag must be paired, no start tag: [ </div> ](tag-pair)

https://github.com/KanadeNishizawa/Portfolio/blob/cf422a4eeacbea9ba7760c4d0e5b0b32d2b6b138/pf.works.html#L148

**Comment by HikaruEgashira** [comment]
[GitHubのIssuesを閉じる方法](https://ushumpei.hatenablog.com/entry/2016/12/20/025249)

**Comment by KanadeNishizawa** [comment]
ありがとうオブザイヤー！！
